### PR TITLE
add penguins_size.csv from https://github.com/allisonhorst/penguins

### PR DESCRIPTION
**Pull request by trenton3983**
- This pull request is to add the penguins_size.csv data from [allisonhorst/penguins/data](https://github.com/allisonhorst/penguins/tree/master/data)

# Palmer Archipelago (Antarctica) penguin data

Data were collected and made available by [Dr. Kristen Gorman](https://www.uaf.edu/cfos/people/faculty/detail/kristen-gorman.php) and the [Palmer Station, Antarctica LTER](https://pal.lternet.edu/), a member of the [Long Term Ecological Research Network](https://lternet.edu/). 

**Thank you** to Dr. Gorman, Palmer Station LTER and the LTER Network! Special thanks to Marty Downs (Director, LTER Network Office) for help regarding the data license & use.

## License & citation

- **Data are available by** [CC-0](https://creativecommons.org/share-your-work/public-domain/cc0/) license in accordance with the [Palmer Station LTER Data Policy](http://pal.lternet.edu/data/policies) and the [LTER Data Access Policy for Type I data](https://lternet.edu/data-access-policy/).

- **Please cite data using the following:**

    - **Adélie penguins:** Palmer Station Antarctica LTER and K. Gorman. 2020. Structural size measurements and isotopic signatures of foraging among adult male and female Adélie penguins (*Pygoscelis adeliae*) nesting along the Palmer Archipelago near Palmer Station, 2007-2009 ver 5. Environmental Data Initiative. https://doi.org/10.6073/pasta/98b16d7d563f265cb52372c8ca99e60f (Accessed 2020-06-08).

    - **Gentoo penguins:** Palmer Station Antarctica LTER and K. Gorman. 2020. Structural size measurements and isotopic signatures of foraging among adult male and female Gentoo penguin (*Pygoscelis papua*) nesting along the Palmer Archipelago near Palmer Station, 2007-2009 ver 5. Environmental Data Initiative. https://doi.org/10.6073/pasta/7fca67fb28d56ee2ffa3d9370ebda689 (Accessed 2020-06-08).

    - **Chinstrap penguins:** Palmer Station Antarctica LTER and K. Gorman. 2020. Structural size measurements and isotopic signatures of foraging among adult male and female Chinstrap penguin (*Pygoscelis antarcticus*) nesting along the Palmer Archipelago near Palmer Station, 2007-2009 ver 6. Environmental Data Initiative. https://doi.org/10.6073/pasta/c14dfcfada8ea13a17536e73eb6fbe9e (Accessed 2020-06-08).

    - **Originally published in:** [**Gorman KB, Williams TD, Fraser WR** (2014) Ecological Sexual Dimorphism and Environmental Variability within a Community of Antarctic Penguins (Genus *Pygoscelis*). PLoS ONE 9(3): e90081. doi:10.1371/journal.pone.0090081](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090081)

### CODE REVIEW

**Comment by mwaskom** [comment]
Thanks! Is it fine to just call it `penguins.csv`?

**Comment by trenton3983** [comment]
My personal preference is `penguins.csv`, but I left it as the original name of the file so as not to create confusion. The original repo has `penguins_lter.csv` and `penguins_size.csv`. With that said, I'll leave it to your discretion.

**Comment by trenton3983** [comment]
Michael, is there anything else I need to do?

**Comment by mwaskom** [comment]
Thanks for the poke. I had pulled your branch and changed the name locally to `penguins.csv` but forgot to push. I think using `penguins` is fine as the existing practice with the repository is to modify the datasets as needed to facilitate seaborn examples (which is the only reason the repository exists).

**Pull request merged**
